### ISSUE TITLE
always doing restart

### ISSUE THREAD

**Issue by fenoloji** [makerbase-mks/MKS-Robin-Nano-Firmware#1]
I compiled the code. But always doing restart. How can i solve?

**Comment by mks-viva** [comment]
Hi, do you mean restart specifically for motherboards?
Our compilation tutorial needs to be improved.

**Comment by fenoloji** [comment]
Yes, motherbord restart.

Also your code "https://github.com/makerbase-mks/MKS-Robin-Nano-Firmware/blob/Nano-firmware-v2.x.x/EWARM/mksRobinNano/Exe/Robin_nano35.bin"  restarting motherboard.

  But "https://github.com/makerbase-mks/MKS-Robin-Nano/blob/master/Nano%20firmware%20v2.x.x/Mks_Nano35_V2.0.0%20Release%20file.rar" in Robin_nano35.bin doesn't restart motherboard.

**Comment by mks-viva** [comment]
I probably know what caused the problem. It may be that the compiled bin file is not transcoded. I will update this tutorial tomorrow. Please wait for my good news. 
I sent you the binEncode_setup.exe installation file. You can use the software to transcode the compiled bin file, and then copy the transcoded bin file to the TF card and insert it into the motherboard for upgrade. Note the bin file name: Robin_nano35.bin

**Comment by fenoloji** [comment]
Hİ, Thank you for your answer. When will you send binEncode_setup.exe to me?

**Comment by makerbase-mks** [comment]
![image](https://user-images.githubusercontent.com/12979070/75732522-a87e9180-5d2d-11ea-88ae-e9af5db19a22.png)
Is it not sent successfully? If so, don't worry. I have updated the tutorial on how to compile the firmware, you can refer to: https://github.com/makerbase-mks/MKS-Robin-Nano-Firmware/wiki/How-to-build-update-nano-firmware

**Comment by fenoloji** [comment]
Hi, all done. Everthings works. You are wonderful.  I want to prepare the Turkish language file and change the code. Would you allow?

**Comment by makerbase-mks** [comment]
You can certainly modify, MKS open source is to serve more enthusiasts. I will close this question for the time being.

**Comment by fenoloji** [comment]
hi,  can you help me?
how can i change the contents of the GBK16.bin
Example;

   orjinal  [cid:78d7c1ee-134f-465e-813e-566255822427] [cid:c7a790ca-3abc-47fc-b41b-fd23eff7b0e1]
                                                                                                                        The shape I want.
________________________________
Gönderen: mks-viva <notifications@github.com>
Gönderildi: 1 Mart 2020 Pazar 16:24
Kime: makerbase-mks/MKS-Robin-Nano-Firmware <MKS-Robin-Nano-Firmware@noreply.github.com>
Bilgi: fenoloji <fenoloji@hotmail.com>; Author <author@noreply.github.com>
Konu: Re: [makerbase-mks/MKS-Robin-Nano-Firmware] always doing restart (#1)


I probably know what caused the problem. It may be that the compiled bin file is not transcoded. I will update this tutorial tomorrow. Please wait for my good news.
I sent you the binEncode_setup.exe installation file. You can use the software to transcode the compiled bin file, and then copy the transcoded bin file to the TF card and insert it into the motherboard for upgrade. Note the bin file name: Robin_nano35.bin

**Comment by makerbase-mks** [comment]
Hi, this is a Chinese character font, you may be not use it. Of course, I can also consult software engineers to see if they can help you solve this problem.

**Comment by JuculianD** [comment]
I think I have the same problem! My display is always restarting. I have encoded it with the software provided!

**Comment by fenoloji** [comment]
> I think I have the same problem! My display is always restarting. I have encoded it with the software provided!

ok. my problem solved.
