### ISSUE TITLE
is possible add light case to graphic interface

### ISSUE THREAD

**Issue by thiodor93** [makerbase-mks/MKS-Robin-Nano-Firmware#20]
hi, I'm not very expert in programming, but even if I activate the light case function, I have no way to use it since I don't have the command on the tft35 display?

**Comment by mks-viva** [comment]
Hi! I want to know, what motherboard and screen are you using?

**Comment by thiodor93** [comment]
Hi i've mks Robin nano 1.2 with makerbase TFT 35 V1.0!
