### ISSUE TITLE
turn off button?

### ISSUE THREAD

**Issue by fenoloji** [makerbase-mks/MKS-Robin-Nano-Firmware#3]
Why is there no button to turn off the machine on the screen?

**Comment by karohan** [comment]
Modül satıyorlar onun için.

**Comment by fenoloji** [comment]
> Modül satıyorlar onun için.

Selamlar, sebep o değil. Biraz düşününce anladım. Ekrandan kapatsak bile açarken bir anahtara ihtiyaç olacak. Ekran kapalı olduğunda nereden açacağız makineyi. Arkadaki kapatma anahtarı zaten açık. oradan açamayız. Demek ki bunun için bir tetikleme anahtarı var. Onu da beraberinde satıyorlar.
    Ekrana kapatma butonu koyulabilir. Ancak açmak için bir tetikleme anahtarına yine ihtiyaç olacak.

**Comment by karohan** [comment]
Türkçe karakter seti ekleyebildin mi ?

**Comment by fenoloji** [comment]
> Türkçe karakter seti ekleyebildin mi ?

Türkçe dil seçeneğini ekledim. Şu anda kendi bilgisayarımda derledim. Çalışıyor. Ancak githuba yüklemedim henüz. Türkçe karakterler bir acayip çıkıyordu. Onları da düzelttim. a harfini el yazısındaki gibi yaptım, ı harfi ve ç harfini de düzelttim.  Bu arada ana ekrana bir mavi çerçeve ekledim.

**Comment by karohan** [comment]
Çok özel değilse paylaşabilir misin? Türkçe karakter sorunu yaşıyorumda

**Comment by fenoloji** [comment]
> Çok özel değilse paylaşabilir misin? Türkçe karakter sorunu yaşıyorumda

Bitmeden paylaşamam. Çalışmamı proje yöneticisine göndericem. Ondan eklemesini isteyeceğim.

**Comment by karohan** [comment]
Peki yinede teşekkür ederim. https://www.facebook.com/groups/1544993445653957/ Grubumuza beklerim ;)

**Comment by JuculianD** [comment]
Hello? I have the same problem. How did you solve???
