### ISSUE TITLE
 how to create icons for the button? 

### ISSUE THREAD

**Issue by ochkariky** [makerbase-mks/MKS-Robin-Nano-Firmware#8]
Hello!
Tell me how to create icons for the button? I tried using the MKS TFT image convert, and bmp size 117x140. but I didn’t succeed. what are the limitations on the original bmp? maybe i use the incorrect version of MKS TFT image convert?
thanks!

**Comment by ochkariky** [comment]
ok. i did.
use MKS_tool/screen2bin.exe

**Comment by makerbase-mks** [comment]
OK! So, i will close this problem.
