### ISSUE TITLE
Marlin version in robin nano firmware

### ISSUE THREAD

**Issue by JinwooJang** [makerbase-mks/MKS-Robin-Nano-Firmware#9]
Hello Makerbase,

Do you have plan to update Marlin codes to latest?
currently, old version 010107 embedded in robin nano firmware.

Thanks.

**Comment by makerbase-mks** [comment]
Hi! You can refer to it : https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware
